### ISSUE TITLE
Profile doesn't show after successful login

### ISSUE THREAD

**Issue by kdbeall** [auth0-samples/auth0-ionic3-samples#3]
When I go into the Auth0 dashboard, it shows a successful login. However, the user profile does not display at all after the successful login. I have tried this on both emulated and real devices and have added an alert. I added it to auth.service.ts in the callback.

```
      let alert = this.alertCtrl.create({
        message: JSON.stringify(authResult)
      });
      alert.present();
```
However, no alert appears. I suspect the ``` this.Client.authorize``` callback isn't working at all.

**Comment by kdbeall** [comment]
I have also made an alert for ```err```

```
      let alert = this.alertCtrl.create({
        message: JSON.stringify(err)
      });
      alert.present();
```

Here's the JSON output from when ```err```

```
{ "crossDomain": true, "method": "POST", "url": "https://myurl.auth0.com/oauth/token", "line":1, "column": 644436, "sourceURL":"http://localhost:8080/var/containers/Bundle/Application/..."},
"code":null, "description":null, "name": "Error"}
```

**Comment by kdbeall** [comment]
Okay... I think I figured out the issue when I checked the auth0 logs. I was running this on a real device, but when I added localhost:8080 to my CORS settings in auth0 it worked. Also, the tutorial above does not mention the Logs section of auth0. That should be added.

**Comment by jimmyjames** [comment]
Closing this issue given the workaround.
